services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/brevly
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brevly
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
